apiVersion: v1
kind: Pod
metadata:
  name: limited-resources-pod
spec:
  containers:
  - name: example-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
 
